
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
	{ on = "A", run = "create --dir", desc = "Create new directory" },
    { on = "R", run = "rename --empty=all", desc = "Rename file" },
    { on = "F", run = "rename --cursor=start", desc = "Rename file" },


	{ on = "K", run = "arrow -10", desc = "Move cursor up" },
	{ on = "J", run = "arrow 10",  desc = "Move cursor down" },

]

